Rome-Blockchain-Labs/terminal-widgets

uniswapv3/src/components/Header/index.tsx, uniswapv3/src/components/NetworkAlert/NetworkAlert.tsx, uniswapv3/src/components/SwitchLocaleLink/index.tsx, uniswapv3/src/i18n.tsx, uniswapv3/src/lib/i18n.tsx
https://romeblockchain.atlassian.net/browse/RT-606?atlOrigin=eyJpIjoiMjQ5NDZjYWIyM2Y1NDY5MDk0NjY4MGRmOGI5OTFmNmIiLCJwIjoiaiJ9
=> RT-606  i18n locale

uniswapv3/src/constants/wallet.ts
https://romeblockchain.atlassian.net/browse/RT-640?atlOrigin=eyJpIjoiN2Y2YzQzODNhY2ZjNGFjMWI2OGQxMzU0ZWI5NTg0ZWEiLCJwIjoiaiJ9
Cant test on the cloud because only one revision can be deployed
Run tests locally
=> RT-640  remove coinbase

trades/src/dapps/dmm/pages/App.tsx, trades/src/dapps/dmm/pages/Pools/index.tsx, trades/src/widgets/Dmm/Widget.tsx
=> kyber from iframe

trades/src/dapps/uniswap-v2/components/IFrameProvider/index.tsx, trades/src/index.tsx, trades/src/widgets/UniswapV2/index.tsx
https://romeblockchain.atlassian.net/browse/RT-719?atlOrigin=eyJpIjoiOGQ2YjMzYTMwYmY1NDU1Yjg5YzhjMWRlMzNlMjU2M2IiLCJwIjoiaiJ9
=> RT 719 setup rome bridge

trades/src/components/modals/TransactionConfirmationModal.tsx, trades/src/dapps/uniswap-v2/App.tsx, trades/src/dapps/uniswap-v2/components/Address.tsx, trades/src/dapps/uniswap-v2/components/CurrencyLogo/index.tsx, trades/src/dapps/uniswap-v2/components/NavigationTab/index.tsx, trades/src/dapps/uniswap-v2/components/WalletModal.tsx, trades/src/dapps/uniswap-v2/pages/Swap/index.tsx, trades/src/dapps/uniswap-v2/token-list/index.ts, trades/src/widgets/UniswapV2/index.tsx
https://romeblockchain.atlassian.net/browse/RT-725?atlOrigin=eyJpIjoiNzMxMzEzYWU0NDg5NDc1ZmE3YTMxMmM3MDM4NTAwOGEiLCJwIjoiaiJ9
=> RT-725 Update modal css

trades/package.json, trades/src/dapps/dmm/pages/Pools/index.tsx, trades/src/dapps/uniswap-v2/pages/AddLiquidity/index.tsx, trades/src/dapps/uniswap-v2/pages/RemoveLiquidity/index.tsx, trades/src/widgets/UniswapV2/index.tsx, trades/src/widgets/Velox/src/components/WalletModal.jsx, trades/src/widgets/Velox/src/containers/ethereum/use-provider.jsx, trades/src/widgets/Velox/src/containers/ethereum/with-provider.jsx, trades/src/widgets/Velox/src/containers/exchange/ConfirmDeploymentSuccessModal.jsx, trades/src/widgets/Velox/src/redux/strategyConfig/strategyConfigSlice.ts, trades/src/widgets/Velox/src/redux/wallet/walletSlice.ts, trades/src/widgets/Velox/src/utils/web3/useEthereumInactiveListener.tsx, trades/src/widgets/Velox/src/utils/web3/useSwitchNetwork.tsx, trades/src/widgets/Velox/src/utils/web3/useWeb3Provider.tsx, trades/src/widgets/Velox/src/utils/web3/walletSelectionContext.tsx, trades/src/widgets/Velox/src/widget/assets/styled.jsx, trades/src/widgets/Velox/src/widget/components/StrategyConfig.tsx, trades/src/widgets/Velox/src/widget/containers/ethereum/use-provider.jsx, trades/src/widgets/Velox/src/widget/containers/ethereum/with-provider.jsx, trades/src/widgets/Velox/src/widget/containers/exchange/ConfirmDeploymentErrorModal.jsx, trades/src/widgets/Velox/src/widget/containers/exchange/ConfirmDeploymentSuccessModal.jsx, trades/src/widgets/Velox/src/widget/index.tsx, trades/yarn.lock
https://romeblockchain.atlassian.net/browse/RT-689?atlOrigin=eyJpIjoiMzk2ZGFiOWRjYzYxNDQ3NmJmZWJkMDQ5ZTgxZjU4Y2QiLCJwIjoiaiJ9
*Note - use production .env values
=> RT-689 Velox IFrame

trades/package.json, trades/src/components/modals/ModalWrapper.tsx, trades/src/dapps/dmm/pages/Pools/index.tsx, trades/src/dapps/uniswap-v2/App.tsx, trades/src/dapps/uniswap-v2/components/Address.tsx, trades/src/dapps/uniswap-v2/components/NavigationTab/index.tsx, trades/src/dapps/uniswap-v2/components/WalletModal.tsx, trades/src/dapps/uniswap-v2/pages/AddLiquidity/index.tsx, trades/src/dapps/uniswap-v2/pages/RemoveLiquidity/index.tsx, trades/src/widgets/UniswapV2/index.tsx, trades/src/widgets/Velox/src/components/WalletModal.jsx, trades/src/widgets/Velox/src/containers/ethereum/use-provider.jsx, trades/src/widgets/Velox/src/containers/ethereum/with-provider.jsx, trades/src/widgets/Velox/src/containers/exchange/ConfirmDeploymentSuccessModal.jsx, trades/src/widgets/Velox/src/redux/strategyConfig/strategyConfigSlice.ts, trades/src/widgets/Velox/src/redux/wallet/walletSlice.ts, trades/src/widgets/Velox/src/utils/web3/useEthereumInactiveListener.tsx, trades/src/widgets/Velox/src/utils/web3/useSwitchNetwork.tsx, trades/src/widgets/Velox/src/utils/web3/useWeb3Provider.tsx, trades/src/widgets/Velox/src/utils/web3/walletSelectionContext.tsx, trades/src/widgets/Velox/src/widget/assets/styled.jsx, trades/src/widgets/Velox/src/widget/components/StrategyConfig.tsx, trades/src/widgets/Velox/src/widget/containers/ethereum/use-provider.jsx, trades/src/widgets/Velox/src/widget/containers/ethereum/with-provider.jsx, trades/src/widgets/Velox/src/widget/containers/exchange/ConfirmDeploymentErrorModal.jsx, trades/src/widgets/Velox/src/widget/containers/exchange/ConfirmDeploymentSuccessModal.jsx, trades/src/widgets/Velox/src/widget/index.tsx, trades/yarn.lock
None
Follow test steps at this PR https://github.com/Rome-Blockchain-Labs/rome-frontend/pull/726
=> Fix fallback to network

trades/src/styles/GlobalStyles.tsx
https://romeblockchain.atlassian.net/browse/RT-730?atlOrigin=eyJpIjoiNTdjODk1ODZjOTlkNDM1MDk3ZWY0OGNiMTNhN2RiOGUiLCJwIjoiaiJ9
=> RT-730 Wallet Connect QR Code Size

trades/src/components/modals/ModalWrapper.tsx, trades/src/contexts/WalletsContext/WalletModal.tsx, trades/src/dapps/uniswap-v2/components/WalletModal.tsx, trades/src/widgets/Velox/src/components/WalletModal.jsx
https://romeblockchain.atlassian.net/browse/RT-728?atlOrigin=eyJpIjoiNWM4NTVkZDM1NTM4NDA5Nzg5N2Q5MGU5NTAwZTViYmEiLCJwIjoiaiJ9
=> RT-728 wallet modal mobile responsive

trades/src/dapps/uniswap-v2/App.tsx, trades/src/widgets/UniswapV2/index.tsx
=> Fix center widget

trades/package.json, trades/src/contexts/WalletsContext/WalletSelectionModal.tsx, trades/src/dapps/dmm/components/Address/index.tsx, trades/src/dapps/dmm/components/AddressModal/index.tsx, trades/src/dapps/dmm/components/WalletModal/index.tsx, trades/src/dapps/dmm/pages/App.tsx, trades/src/dapps/dmm/state/application/actions.ts, trades/src/dapps/dmm/state/application/hooks.ts, trades/src/dapps/dmm/state/application/reducer.ts, trades/src/dapps/uniswap-v2/App.tsx, trades/src/dapps/uniswap-v2/PageContext.tsx, trades/src/dapps/uniswap-v2/components/AddressModal.tsx, trades/src/dapps/uniswap-v2/components/WalletModal.tsx, trades/src/dapps/uniswap-v2/state/index.ts, trades/src/store/index.ts, trades/src/store/slices/app.ts, trades/src/styles/GlobalStyles.tsx, trades/src/widgets/UniswapV2/index.tsx, trades/src/widgets/Velox/src/components/WalletModal.jsx, trades/src/widgets/Velox/src/utils/web3/useSwitchNetwork.tsx, trades/src/widgets/Velox/src/widget/components/Step1SelectExchange.jsx, trades/src/widgets/Velox/src/widget/containers/ethereum/use-provider.jsx, trades/yarn.lock
=> Fix: Add network to wallet when missing when connecting through Wallet Connect 

banxa/hooks/useCurrencyList.ts, banxa/hooks/useGetPrice.ts, banxa/pages/create-order.tsx
Add blockchain select field on buy and sell orders
https://banxa-h5axcfkrgq-uc.a.run.app/ to test
=> Add blockchain input

banxa/pages/api/banxa/webhook.ts, banxa/pages/order/[orderID].tsx
- do not send emails for sell orders without wallet address
- display pending notification when order is waiting payment and no wallet address or pending payment
=> Update webhook logic, display pending status

trades/package.json, trades/src/dapps/uniswap-v2/App.tsx, trades/src/dapps/uniswap-v2/components/Address.tsx, trades/yarn.lock
- display wallet icon to notify user which wallet he is using
- on hover, display wallet address
- on click give option to disconnect from wallet
- allow wallet icon to be draggable in the X-axis
To test
https://wallet---rt-sand-h5axcfkrgq-uc.a.run.app/
1. connect using either metamask or wallet connect when connecting to pangolin or any other univ2clone widget
2. expect to see wallet icon on upper left corner
=> feat: use framer-motion to make wallet icon draggable

banxa/pages/create-order.tsx
Users should not be able to toggle to the sell page
https://banxa.rometerminal.io/
=> Comment out sell orders

venus/.storybook/preview.js, venus/src/assets/styles/App.scss, venus/src/assets/styles/Global.scss, venus/src/components/v2/AuthModal/index.stories.tsx, venus/src/components/v2/EnableToken/styles.ts, venus/src/components/v2/Modal/index.tsx, venus/src/components/v2/Modal/styles.ts, venus/src/components/v2/ProgressBar/LabeledProgressBar/styles.tsx, venus/src/components/v2/Tabs/styles.tsx, venus/src/components/v2/TextField/styles.ts, venus/src/pages/Dashboard/Markets/styles.ts, venus/src/pages/Dashboard/Modals/BorrowRepay/Repay/styles.ts, venus/src/pages/Dashboard/Modals/BorrowRepay/index.tsx, venus/src/pages/Dashboard/Modals/SupplyWithdraw/SupplyWithdrawForm.tsx, venus/src/pages/Dashboard/Modals/SupplyWithdraw/index.tsx, venus/src/pages/Dashboard/Modals/styles.ts, venus/src/pages/Dashboard/MyAccount/styles.ts, venus/src/stories/decorators.tsx
Style the borrow and repay modals
https://romeblockchain.atlassian.net/jira/software/c/projects/RT/boards/6?modal=detail&selectedIssue=RT-901
New feature (non-breaking change which adds functionality)
- Open the venus widget
- Open borow and repay modals
- Open enable modal
=> RT-900 - Implement Venus Protocol Asset Borrow and Repay actions

venus/package.json, venus/yarn.lock
Revert "build(deps): bump node-forge, react-scripts, webpack-dev-server and @storybook/preset-create-react-app in /venus (#94)"
This reverts commit 2e524c4e03d4f30cdd9fc0e373d0139986bdcd1a.
=> Fix Venus build issue

trades/package.json, trades/src/dapps/dmm/components/WalletModal/index.tsx, trades/src/dapps/uniswap-v2/components/WalletModal.tsx, trades/src/dapps/uniswap-v2/hooks/useSwapCallback.ts, trades/yarn.lock
=> fix: import latest bridge and hack type match for bridge

venus/.eslintrc.js, venus/package.json, venus/src/clients/api/mutations/useBorrowVToken.ts, venus/src/clients/api/mutations/useRepayBnb.ts, venus/src/clients/api/mutations/useRepayNonBnbVToken.ts, venus/src/clients/api/mutations/useSupplyBnb.ts, venus/src/clients/api/mutations/useSupplyNonBnb.ts, venus/yarn.lock
- Add events for supply, borrow, and repay transactions
=> RT-1066 add venus widget bridge events

banxa/components/auth/Login.tsx, banxa/components/auth/Registration.tsx, banxa/pages/forgot-password.tsx, banxa/pages/index.tsx, banxa/pages/reset-password.tsx
- fix divider gradient
- added vertical padding
- remove h-full and w-full to properly display top and bottom sections
To test
https://banxa-sandbox-h5axcfkrgq-uc.a.run.app/
resize window to widget size around 375 px width and 400 px length
test for responsiveness
=> RT-1082 Fix Banxa Mobile UI issues

banxa/Context/IFrameContext.tsx, banxa/package.json, banxa/pages/create-order.tsx, banxa/pnpm-lock.yaml
- event name: banxa_buy_order or banxa_sell_order
https://docs.google.com/spreadsheets/d/1vVmCcY-jjeOejKUjDmmgCOtY1V49n-3IlBqgnAlGCrc/edit#gid=0 updated
=> RT-1060 Send analytics data on order create

trades/src/dapps/uniswap-v2/token-list/avalanche/traderjoe.ts
- update link to traderjoe token list
https://romeblockchain.atlassian.net/browse/RT-1441
Bug fix (non-breaking change which fixes an issue)
- Open traderjoe swap widget
=> RT-1441 - Investigate tokens list missing on Trader Joe Dex Widget
